// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvKercImltVCCaFaH7v-ggSc6QG9i7X0',
    appId: '1:1032196092488:web:774bba0afc382e81f65e7d',
    messagingSenderId: '1032196092488',
    projectId: 'instax-eb2b8',
    authDomain: 'instax-eb2b8.firebaseapp.com',
    storageBucket: 'instax-eb2b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7dihd4eNeVSalBtqWBWTh2q0biMmxchU',
    appId: '1:1032196092488:android:08919bccab3577c2f65e7d',
    messagingSenderId: '1032196092488',
    projectId: 'instax-eb2b8',
    storageBucket: 'instax-eb2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kCIMc4AFDCj7uhpuQSCi3Uf1KfFHlqE',
    appId: '1:1032196092488:ios:65900ccd1798a9c7f65e7d',
    messagingSenderId: '1032196092488',
    projectId: 'instax-eb2b8',
    storageBucket: 'instax-eb2b8.appspot.com',
    iosBundleId: 'com.example.instax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2kCIMc4AFDCj7uhpuQSCi3Uf1KfFHlqE',
    appId: '1:1032196092488:ios:3f9a67433f79eef6f65e7d',
    messagingSenderId: '1032196092488',
    projectId: 'instax-eb2b8',
    storageBucket: 'instax-eb2b8.appspot.com',
    iosBundleId: 'com.example.instax.RunnerTests',
  );
}
